name: build-test-deploy
on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version"
        type: string
        required: true

jobs:
  build:
    runs-on: [self-hosted, linux, dev]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - run: npm install
      - run: npm run build

  test:
    runs-on: [self-hosted, linux, dev]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - run: npm install
      - run: npm run test
      
