# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-test-dotnet

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: ".NET version"
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Install Dependencies
      run: |
        cd src/VMS.MainService
        dotnet restore
    - name: Build
      run: |
        cd src/VMS.MainService
        dotnet build --no-restore
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Test
  #       run: dotnet test --no-build
  
